"""
Agent Health & Watchdog Monitor.

Tracks real-time heartbeats from 24/7 cloud daemons, detects unresponsive
or hung agent processes, and triggers automated self-healing procedures.
"""

from __future__ import annotations
import time
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional


@dataclass
class AgentHeartbeat:
    """Telemetry pulse emitted by an active agent daemon."""
    agent_id: str
    status: str = "HEALTHY"  # "HEALTHY", "DEGRADED", "CRITICAL"
    metrics: Dict[str, any] = field(default_factory=dict)
    last_seen: float = field(default_factory=time.time)


@dataclass
class WatchdogAlert:
    """An alert generated by the watchdog monitor."""
    agent_id: str
    alert_type: str  # "STALE_HEARTBEAT", "DEGRADED_PERFORMANCE", "RESTART_TRIGGERED"
    details: str
    timestamp: float = field(default_factory=time.time)


RecoveryAction = Callable[[str], None]


class HealthMonitor:
    """
    Supervises background agent worker processes and executes self-healing.
    """

    def __init__(self, timeout_seconds: float = 5.0, on_recovery: Optional[RecoveryAction] = None):
        self.timeout_seconds = timeout_seconds
        self.on_recovery = on_recovery
        self._agents: Dict[str, AgentHeartbeat] = {}
        self._alerts: List[WatchdogAlert] = []

    def record_heartbeat(
        self, agent_id: str, status: str = "HEALTHY", metrics: Optional[Dict] = None
    ) -> None:
        """Register a heartbeat from an agent."""
        self._agents[agent_id] = AgentHeartbeat(
            agent_id=agent_id,
            status=status,
            metrics=metrics or {},
            last_seen=time.time(),
        )

    def check_health(self) -> List[WatchdogAlert]:
        """
        Scan all monitored agents and detect dead or degraded daemons.
        """
        now = time.time()
        new_alerts = []

        for agent_id, hb in list(self._agents.items()):
            time_since_seen = now - hb.last_seen

            if time_since_seen > self.timeout_seconds:
                alert = WatchdogAlert(
                    agent_id=agent_id,
                    alert_type="STALE_HEARTBEAT",
                    details=f"Agent '{agent_id}' silent for {time_since_seen:.2f}s (timeout: {self.timeout_seconds}s)",
                )
                new_alerts.append(alert)
                self._alerts.append(alert)

                # Trigger automated recovery if configured
                if self.on_recovery:
                    self.on_recovery(agent_id)
                    recovery_alert = WatchdogAlert(
                        agent_id=agent_id,
                        alert_type="RESTART_TRIGGERED",
                        details=f"Self-healing restart invoked for agent '{agent_id}'",
                    )
                    new_alerts.append(recovery_alert)
                    self._alerts.append(recovery_alert)

        return new_alerts

    def get_agent_status(self, agent_id: str) -> Optional[AgentHeartbeat]:
        return self._agents.get(agent_id)
